spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
#      uri: mongodb://localhost:27017/spring_boot
      host: localhost
      port: 27017
      database: sprint_boot
#      username:
#      password:

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000 #连接超时时间(毫秒)
    pool:
      # 连接池中的最小空闲连接
      min-idle: 8
      # 连接池中的最大空闲连接
      max-idle: 200
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 1024
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 10000
