spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
#      uri: mongodb://localhost:27017/spring_boot
      host: localhost
      port: 27017
      database: sprint_boot
#      username:
#      password:

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true

  redis:
    host: localhost
    port: 6379
    password:
